public class ExceptionSample {
    public static void main(String[] args) {
        try {
            int divideByZero = 5/0;
        } catch (ArithmeticException e){
        System.out.println("Arithmetic Exception: cannot divide by zero! "+e.getMessage());
        } finally {
            System.out.println("Finally block executed");
    }
}
}